xset r rate 150 40
xset s 1800 1800 -dpms
$MY_DOTFILES_REPO/scripts/configure-monitors
exec unclutter --timeout 1 --start-hidden --ignore-scrolling --jitter 10 &
exec slstatus &
exec dunst &
exec dwm
