filetype off                     " Disable file type detection
syntax enable                    " Enable syntax highting
set background=dark              " Enable dark mode
set encoding=utf-8               " Enable unicode
set nocompatible                 " Disable vi compatibility
set ttimeout                     " Insert mode escape sequence timeout
set ttimeoutlen=100              " Short insert mode escape sequence timeout
set hlsearch                     " Highlight search matches
set incsearch                    " Interactive search highlight
set ignorecase                   " Enable case insensitive search
set relativenumber               " Enable relative line numbers
set number                       " Absolute line number for current line
set nowrap                       " Do not wrap long lines
set smartindent                  " Automatically indent new lines
set tabstop=4                    " Tabs appear as 4 spaces
set shiftwidth=4                 " Set indentation to 4 spaces
set expandtab                    " Convert tabs to spaces
set scrolloff=10                 " Vertical scrolloff
set sidescrolloff=20             " Horizontal scrolloff
set shortmess+=I                 " Disable intro message
set viminfo=                     " Disable viminfo
let g:netrw_banner=0             " Disable Netrw help banner
let g:netrw_list_hide="^\\.\\/$" " Disable current directory
let g:netrw_cursor=0             " Disable cursorline in Netrw
let g:mapleader=" "              " Set the leader key

" Explore with Netrw
nnoremap <Leader>e <Cmd>Explore<Return>

" Toggle search highlight
nnoremap <Leader>h <Cmd>set hlsearch!<Return>

" Toggle line number visibility
nnoremap <Leader>n <Cmd>set number!<Return><Cmd>set relativenumber!<Return>

" Stay in visual mode on indent/dedent
vnoremap < <gv
vnoremap > >gv

" Search and replace
nnoremap <C-s> :%substitute//g<Left><Left>
vnoremap <C-s> :substitute//g<Left><Left>

" Count search results
nnoremap <C-n> :%substitute///gn<Left><Left><Left><Left>
vnoremap <C-n> :substitute///gn<Left><Left><Left><Left>

" Clear current search highlight
nnoremap <Return> <Cmd>nohlsearch<Return>

" Tab controls
nnoremap <C-t>   <Cmd>tabnew<Return>
nnoremap <C-q>   <Cmd>tabclose<Return>
nnoremap <Tab>   <Cmd>tabnext<Return>
nnoremap <S-Tab> <Cmd>tabprevious<Return>
nnoremap g<      <Cmd>tabmove -1<Return>
nnoremap g>      <Cmd>tabmove +1<Return>

nnoremap <Leader>1 1gt
nnoremap <Leader>2 2gt
nnoremap <Leader>3 3gt
nnoremap <Leader>4 4gt
nnoremap <Leader>5 5gt
nnoremap <Leader>6 6gt
nnoremap <Leader>7 7gt
nnoremap <Leader>8 8gt
nnoremap <Leader>9 9gt

" https://vim.fandom.com/wiki/Moving_lines_up_or_down
nnoremap <silent> <C-k> :move .-2<Return>==
nnoremap <silent> <C-j> :move .+1<Return>==
vnoremap <silent> <C-k> :move '<-2<Return>gv=gv
vnoremap <silent> <C-j> :move '>+1<Return>gv=gv

" Write and quit
nnoremap <Leader>w <Cmd>w<Return>
nnoremap <Leader>q <Cmd>q<Return>
nnoremap <Leader>x <Cmd>x<Return>

" Try to keep the cursor centered
noremap G Gzz
noremap n nzz
noremap N Nzz
noremap <C-d> <C-d>zz
noremap <C-u> <C-u>zz
noremap { {zz
noremap } }zz
