set nocompatible                 " Disable vi compatibility. Keep at the top.
set background=dark              " Dark mode
set encoding=utf-8               " Unicode
set ttimeout                     " Insert mode escape sequence timeout
set ttimeoutlen=100              " Short insert mode escape sequence timeout
set hlsearch                     " Highlight search matches
set incsearch                    " Interactive search highlight
set ignorecase                   " Enable case insensitive search
set relativenumber               " Enable relative line numbers
set number                       " Absolute line number for current line
set smartindent                  " Automatically indent new lines
set tabstop=4                    " Tabs appear as 4 spaces
set shiftwidth=4                 " Set indentation to 4 spaces
set expandtab                    " Convert tabs to spaces
set scrolloff=10                 " Vertical scrolloff
set sidescrolloff=30             " Horizontal scrolloff
set virtualedit=block            " Allow going past the end of line in visual block mode
set wildmenu                     " Show command line completions list
set path+=**                     " Recursively find in subdirectories
set nowrap                       " Do not wrap long lines
set splitkeep=topline            " Do not scroll when resizing horizontal splits
set nostartofline                " Do not move the the cursor to the start of the line on vertical movements
set shortmess+=I                 " Disable intro message
set viminfo=                     " Disable viminfo
set nomodeline                   " Disable unnecessary feature
let g:netrw_banner=0             " Disable Netrw help banner
let g:netrw_list_hide="^\\.\\/$" " Disable current directory
let g:netrw_cursor=0             " Disable cursorline in Netrw
let g:mapleader=" "              " Set the leader key
filetype off                     " Disable file type detection
syntax enable                    " Enable syntax highting

" Explore with Netrw
nnoremap <Leader>e     <Cmd>Explore<Return>
nnoremap <Leader>E     <Cmd>Sexplore<Return>
nnoremap <Leader><C-e> <Cmd>Texplore<Return>

" Find files
nnoremap <Leader>f :find<Space>

" Toggle search highlight
nnoremap <Leader>h <Cmd>set hlsearch!<Return>

" Toggle line number visibility
nnoremap <Leader>n <Cmd>set number!<Return><Cmd>set relativenumber!<Return>

" Jumplist navigation
nnoremap <Leader>j <C-o>zz
nnoremap <Leader>k <C-i>zz

" Search and replace
nnoremap <C-s> :%substitute//g<Left><Left>
vnoremap <C-s> :substitute//g<Left><Left>

" Clear current search highlight
nnoremap <Esc> <Cmd>nohlsearch<Return>

" Tab controls
nnoremap <C-t>     <Cmd>tabnew<Return>
nnoremap <C-q>     <Cmd>tabclose<Return>
nnoremap <Tab>     <Cmd>tabnext<Return>
nnoremap <S-Tab>   <Cmd>tabprevious<Return>
nnoremap g<        <Cmd>tabmove -1<Return>
nnoremap g>        <Cmd>tabmove +1<Return>
nnoremap <Leader>1 1gt
nnoremap <Leader>2 2gt
nnoremap <Leader>3 3gt
nnoremap <Leader>4 4gt
nnoremap <Leader>5 5gt
nnoremap <Leader>6 6gt
nnoremap <Leader>7 7gt
nnoremap <Leader>8 8gt
nnoremap <Leader>9 9gt
nnoremap <Leader>0 g<Tab>

" Move selected lines up and down
vnoremap <silent> <C-k> :move '<-2<Return>gv=gv
vnoremap <silent> <C-j> :move '>+1<Return>gv=gv

" Window resizing
nnoremap <C-j> <Cmd>resize -1<Return>
nnoremap <C-k> <Cmd>resize +1<Return>
nnoremap <C-h> <Cmd>vertical resize -2<Return>
nnoremap <C-l> <Cmd>vertical resize +2<Return>

" Stay in visual mode on indent/dedent
vnoremap < <gv
vnoremap > >gv

" Write and quit
nnoremap <Leader>w <Cmd>write<Return>
nnoremap <Leader>q <Cmd>quit<Return>

" Scroll in insert mode
inoremap <C-e> <C-o><C-e>
inoremap <C-y> <C-o><C-y>

" Center the cursor in insert mode
inoremap <C-z> <C-o>zz

" Do not save paragraph jumps to the jumplist
nnoremap { <Cmd>execute "keepjumps normal!" . v:count1 . "{zz"<Return>
vnoremap { <Cmd>execute "keepjumps normal!" . v:count1 . "{zz"<Return>
nnoremap } <Cmd>execute "keepjumps normal!" . v:count1 . "}zz"<Return>
vnoremap } <Cmd>execute "keepjumps normal!" . v:count1 . "}zz"<Return>

" Try to keep the cursor centered
nnoremap G Gzz
vnoremap G Gzz
nnoremap n nzz
vnoremap n nzz
nnoremap N Nzz
vnoremap N Nzz
nnoremap <C-d> <C-d>zz
vnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
vnoremap <C-u> <C-u>zz

" Yank to the end of line (behave like C and D)
nnoremap Y y$

function s:ApplyHelpBufferOptions()
    nnoremap <buffer> j  <C-e>
    nnoremap <buffer> J 3<C-e>
    nnoremap <buffer> k  <C-y>
    nnoremap <buffer> K 3<C-y>
    nnoremap <buffer> q <Cmd>quit<Return>
endfunction

autocmd FileType help call s:ApplyHelpBufferOptions()
