filetype off                          " Disable file type detection

syntax enable                         " Enable syntax highting

colorscheme koehler                   " Color preferences

nnoremap \h :set hlsearch!<return>"   " Toggle search highlight
nnoremap \n :set number!<return>"     " Toggle line numbers

set incsearch                         " Interactive search highlight
set ignorecase                        " Enable case insensitive search

set number                            " Enable line numbers

set encoding=utf-8                    " Enable unicode

set smartindent                       " Automatically indent new lines

set foldmethod=syntax                 " Enable syntax-based code folding
set foldlevelstart=30                 " Don't fold files by default

set nocompatible                      " Disable vi compatibility
set noesckeys                         " Disable insert mode escape sequences

set undofile                          " Enable persistent undo

set tabstop=4                         " Tabs appear as 4 spaces
set shiftwidth=4                      " Set indentation to 4 spaces
set expandtab                         " Convert tabs to spaces

" Set swap, undo, and backup directories
set directory=$XDG_CACHE_HOME/vim/swap
set undodir=$XDG_CACHE_HOME/vim/undo
set backupdir=$XDG_CACHE_HOME/vim/backup
