version = "Two"
chain_width = 100
array_width = 100
fn_call_width = 100
struct_lit_width = 100
single_line_if_else_max_width = 100
where_single_line = true
control_brace_style = "ClosingNextLine"
imports_granularity = "Module"
imports_layout = "Horizontal"
