#!/bin/bash
# shellcheck disable=SC1091 # shellcheck can not follow the sources

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Set dotfiles repo location
export MY_DOTFILES_REPO=$HOME/misc/dotfiles

# Stop here if the dotfiles repo was not found
if [ ! -e "$MY_DOTFILES_REPO" ]
then
    echo "dotfiles repo not found"
    return
fi

source "$MY_DOTFILES_REPO/configs/bash/variables"
source "$MY_DOTFILES_REPO/configs/bash/default-cli-arguments"
source "$MY_DOTFILES_REPO/configs/bash/convenience-aliases"
source "$MY_DOTFILES_REPO/configs/bash/utility-functions"

# Added by ghcup
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env
