#!/bin/bash

alias q='exit'
alias md='mkdir -pv'
alias rd='rmdir -v'
alias sv='sudo vim'
alias sdn='shutdown now'
alias ubl='rfkill unblock bluetooth'
alias lsn='mpv --no-video --shuffle --loop-playlist --volume=80'
alias calendar='cal $(date +%Y)'
alias memcheck='valgrind --leak-check=full --show-leak-kinds=all -s'
alias yt-dlp-audio='yt-dlp --extract-audio --audio-format mp3 --audio-quality 0'

alias r='ctest --rerun-failed --output-on-failure'
alias n='ninja'
alias t='n && (ctest --progress || r)'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
