#!/bin/bash

alias ls='ls -h --color=auto --group-directories-first'
alias cp='cp -iv'
alias mv='mv -iv'
alias rg='rg -i'
alias md='mkdir -pv'
alias rd='rmdir -v'
alias pwd='pwd -P'
alias cal='cal --monday'
alias grep='grep -i --color=auto'
alias onefetch='onefetch --true-color=always'
