#!/bin/bash

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'
alias rg='rg -i'
alias pwd='pwd -P'
alias cal='cal --monday'
alias ghci='ghci -v0'
alias grep='grep -i --color=auto'
alias onefetch='onefetch --true-color=always'
