#!/bin/bash

# Make and change directory (mkdir + cd)
mc () {
    if [ "$#" != "1" ]; then
        echo "mc: Expected exactly one argument" 1>&2
        return 1
    elif [ -d "$1" ]; then
        cd -- "$1" || exit
        echo "Moved to existing $(pwd)"
    else
        mkdir -p -- "$1"
        cd -- "$1" || exit
        echo "Created and moved to $(pwd)"
    fi
}
