#!/bin/bash

# Primary and continuation prompt
PS1="$ "
PS2="> "

# Add custom scripts to PATH
export PATH=$MY_DOTFILES_REPO/scripts:$PATH

# Disable logging of duplicate and exit commands
export HISTCONTROL=ignoredups
export HISTIGNORE='q:exit'

# Default editor and browser
export EDITOR=nvim
export BROWSER=firefox

# Miscellaneous app configuration
export PYTHONSTARTUP="$MY_DOTFILES_REPO/configs/python/startup.py"
export LESSHISTFILE=/dev/null
export SQLITE_HISTORY=/dev/null
export WATCH_INTERVAL=0.1
export MANPAGER="nvim +Man!"

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Config and state locations for apps that don't respect XDG
export HISTFILE="$XDG_STATE_HOME/bash/history"
export INPUTRC="$MY_DOTFILES_REPO/configs/readline/inputrc"
export XINITRC="$MY_DOTFILES_REPO/configs/x/xinitrc"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# shellcheck disable=1091
source "$HOME/.ghcup/env"
