#!/bin/bash

# Set primary and continuation prompt
PS1="$ "
PS2="> "

# Add custom scripts to PATH
export PATH=$MY_DOTFILES_REPO/scripts:$PATH

# Disable logging of duplicate and exit commands
export HISTCONTROL=ignoredups
export HISTIGNORE='q:exit'

# Set default editor and browser
export EDITOR=vim
export BROWSER=firefox

# Disable python, less, and sqlite history
export PYTHONSTARTUP="$MY_DOTFILES_REPO/configs/python/startup.py"
export LESSHISTFILE=/dev/null
export SQLITE_HISTORY=/dev/null


export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export HISTFILE="$XDG_STATE_HOME/bash/history"
export XINITRC="$MY_DOTFILES_REPO/configs/x/xinitrc"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export OPAMROOT="$XDG_DATA_HOME/opam"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# shellcheck disable=1091
source "$HOME/.ghcup/env"
