#!/bin/sh

# $1: Status
battery () {
    cat "/sys/class/power_supply/BAT0/$1"
}

# $1: File path, must exist
seconds_since_touch () {
    currenttime=$(date +%s)
    touchtime=$(stat --format=%Y -- "$1")
    echo $((currenttime - touchtime))
}

# $1: Integer percentage
# $2: Optional urgency
warn_if_less_than () {
    [ "$(battery capacity)" -le "$1" ] || return
    timestamp=/tmp/dotfiles-battery-sentry-$1-warning-timestamp
    if [ ! -f "${timestamp}" ] || [ "$(seconds_since_touch "${timestamp}")" -ge 900 ]; then
        # 15 minutes since last warning
        touch "${timestamp}"
        notify-send --urgency="${2:-normal}" "Battery: $(battery capacity)%"
        true
    fi
    false
}

while true; do
    if [ "$(battery status)" = Discharging ]; then
        warn_if_less_than 30 critical || warn_if_less_than 70 normal
    fi
    sleep 299 # Check every 5 minutes
done
