#!/bin/sh


looks_like_a_url () {
    case "$1" in
        "https://"*)
            return 0;;
        *)
            return 1;;
    esac
}

prompt_yesno () {
    case $(printf "yes\nno" | dmenu -i -p "$1") in
        "yes")
            return 0;;
        "no")
            return 1;;
        "")
            notify-send Error "No choice made, aborting"
            exit 1;;
        *)
            prompt_yesno "$1";;
    esac
}


bookmarks="$HOME/misc/bookmarks"
if [ ! -e "$bookmarks" ]
then
    notify-send Error "Bookmarks directory not found"
    exit 1
fi

filechoices=$(echo "[all]" && find "$bookmarks" -type f -exec basename {} \;)
bookmarkfile=$(echo "$filechoices" | dmenu -i -p "Which bookmark file?")

if [ -z "$bookmarkfile" ]
then
    notify-send Notice "No bookmark file selected"
    exit 1
fi

if [ "$bookmarkfile" = "[all]" ]
then
    bookmarklist=$(cat "$bookmarks"/*)
elif [ -e "$bookmarks/$bookmarkfile" ]
then
    bookmarklist=$(cat "$bookmarks/$bookmarkfile")
else
    notify-send Error "Bookmark file \"$bookmarkfile\" does not exist"
    exit 1
fi

bookmarkchoice=$(echo "$bookmarklist" | dmenu -i -l 5)
if [ -z "$bookmarkchoice" ]
then
    notify-send Notice "No bookmark selected"
    exit 1
fi

if looks_like_a_url "$bookmarkchoice" && prompt_yesno "Open in browser?"
then
    if [ -n "$BROWSER" ]
    then
        $BROWSER "$bookmarkchoice"
    else
        notify-send Error "\$BROWSER is not defined"
        exit 1
    fi
else
    printf %s "$bookmarkchoice" | xclip -selection clipboard
    notify-send Success "Copied bookmark to clipboard"
fi
