#!/bin/sh

##@ param Message
notify () { command notify "bookmark-add" "$1"; }

##@ param Message
error () { notify "Error: $1"; exit 1; }

selection=$(xclip -out -rmlastnl)
if [ -n "${selection}" ]; then
    notify "Current selection: ${selection}"
else
    error "No selection"
fi

bookmarkdirectory=${HOME}/misc/bookmarks
[ -d "${bookmarkdirectory}" ] || error "${bookmarkdirectory} does not exist"
bookmarkname=$(find "${bookmarkdirectory}" -type f -printf "%f\\n" | choice-menu "Save where?")
[ -n "${bookmarkname}" ] || error "No bookmark file selected"

if grep --quiet --fixed-strings --line-regexp "${selection}" "${bookmarkdirectory}/${bookmarkname}"; then
    notify "Already bookmarked"
else
    echo "${selection}" >> "${bookmarkdirectory}/${bookmarkname}"
    notify "Bookmark saved to ${bookmarkname}"
fi
