#!/bin/sh

# $1: Message
notify () {
    notify-send "bookmark-open" "$1"
}

# $1: String to examine
looks_like_a_url () {
    case $1 in
        "https://"*)
            return 0;;
        *)
            return 1;;
    esac
}

# $1: Prompt string
prompt_yesno () {
    case $(printf "yes\nno" | dmenu -i -p "$1") in
        "yes")
            return 0;;
        "no")
            return 1;;
        "")
            notify "Error: No choice made, aborting"
            exit 1;;
        *)
            prompt_yesno "$1";;
    esac
}


bookmarks="${HOME}/misc/bookmarks"
if [ ! -e "${bookmarks}" ]; then
    notify "Error: Bookmarks directory not found"
    exit 1
fi

filechoices=$(echo "[all]" && find "${bookmarks}" -type f -printf "%f\\n")
bookmarkfile=$(echo "${filechoices}" | dmenu -i -p "Which bookmark file?")

if [ -z "${bookmarkfile}" ]; then
    notify "No bookmark file selected"
    exit 1
fi

if [ "${bookmarkfile}" = "[all]" ]; then
    bookmarklist=$(cat "${bookmarks}"/*)
elif [ -e "${bookmarks}/${bookmarkfile}" ]; then
    bookmarklist=$(cat "${bookmarks}/${bookmarkfile}")
else
    notify "Error: Bookmark file \"${bookmarkfile}\" does not exist"
    exit 1
fi

bookmarkchoice=$(echo "${bookmarklist}" | dmenu -i -l 5)
if [ -z "${bookmarkchoice}" ]; then
    notify "No bookmark selected"
    exit 1
fi

if looks_like_a_url "${bookmarkchoice}" && prompt_yesno "Open in browser?"; then
    if [ -n "${BROWSER}" ]; then
        "${BROWSER}" "${bookmarkchoice}"
    else
        notify "Error: \$BROWSER is not defined"
        exit 1
    fi
else
    printf %s "${bookmarkchoice}" | xclip -selection clipboard
    notify "Copied bookmark to clipboard"
fi
