#!/bin/sh

# $1: Message
notify () {
    notify-send --expire-time=2000 "bookmark-add" "$1"
}

selection=$(xclip -out -rmlastnl)
if [ -n "${selection}" ]; then
    notify "Current selection: ${selection}"
else
    notify "Error: No selection"
    exit 1
fi

bookmarks="${HOME}/misc/bookmarks"
if [ ! -e "${bookmarks}" ]; then
    notify "Error: Bookmarks directory not found"
    exit 1
fi

bookmarkfile=$(find "${bookmarks}" -type f -printf "%f\\n" | dmenu -i -p "Save where?")
if [ -z "${bookmarkfile}" ]; then
    notify "No bookmark file selected"
    exit 1
fi

if grep --quiet --fixed-strings --line-regexp "${selection}" "${bookmarks}/${bookmarkfile}"; then
    notify "Already bookmarked"
else
    echo "${selection}" >> "${bookmarks}/${bookmarkfile}"
    notify "Bookmark saved to ${bookmarkfile}"
fi
