#!/bin/sh

##@ param Message
error () { notify "bookmark-open" "Error: $1"; exit 1; }

##@ param String
looks_like_a_url () {
    case $1 in
        "https://"*) true;;
        "http://"*)  true;;
        *)           false;;
    esac
}

bookmarkdirectory=${HOME}/misc/bookmarks
[ -d "${bookmarkdirectory}" ] || error "Bookmark directory does not exist: '${bookmarkdirectory}'"

options=$(echo "[all]" && find "${bookmarkdirectory}" -type f -printf "%f\\n")
bookmarkfile=$(echo "${options}" | choice-menu "Which bookmark file?")
[ -n "${bookmarkfile}" ] || error "No bookmark file selected"

if [ "${bookmarkfile}" = "[all]" ]; then
    bookmarklist=$(cat "${bookmarkdirectory}"/*)
elif [ -f "${bookmarkdirectory}/${bookmarkfile}" ]; then
    bookmarklist=$(cat "${bookmarkdirectory}/${bookmarkfile}")
else
    error "Bookmark file does not exist: '${bookmarkfile}'"
fi

choice=$(echo "${bookmarklist}" | choice-menu "Which bookmark?") || error "No bookmark selected"

if looks_like_a_url "${choice}"; then
    handle-url "${choice}"
else
    clip "${choice}"
fi
