#!/bin/sh

##@ param New brightness
control () {
    brightnessctl set "$1"
    notify-send --expire-time=250 "New brightness" "$(brightnessctl get)%"
}

case $1 in
    up)   control 5%+;;
    down) control 5%-;;
    *)    notify "change-brightness" "Error: Invalid argument"; exit 1;;
esac
