#!/bin/sh

apply_default () {
    xset r rate 660 30
    setxkbmap -layout "fi" -option
    pkill --exact unclutter
}

apply_custom () {
    xset r rate 175 60
    setxkbmap -layout "us" -option caps:swapescape
    unclutter --fork --timeout=1 --jitter=10 --start-hidden --ignore-scrolling
}

toggle () {
    if ! pidof -q unclutter; then
        apply_custom
        notify "Custom settings applied"
    else
        apply_default
        notify "Default settings restored"
    fi
}

case $1 in
    default) apply_default;;
    custom)  apply_custom;;
    toggle)  toggle;;
    *)       exit 1;;
esac
