#!/bin/sh

##@ param Message
error () { notify "configure-monitors" "Error: $1"; exit 1; }

##@ param Primary monitor name
##@ param Secondary monitor name
auto_configure () {
    if xrandr --listmonitors | grep --quiet --fixed-strings "$1"; then
        xrandr --output "$1" --auto --output "$2" --off
    fi
}

##@ param Primary monitor name
##@ param Secondary monitor name
##@ param Configuration
configure () {
    case $3 in
        1)    xrandr --output "$1" --auto --output "$2" --off;;
        2)    xrandr --output "$1" --off --output "$2" --auto;;
        12)   xrandr --output "$1" --auto --output "$2" --auto --right-of "$1";;
        21)   xrandr --output "$1" --auto --output "$2" --auto --left-of "$1";;
        11)   xrandr --output "$1" --auto --output "$2" --auto --same-as "$1";;
        auto) auto_configure "$1" "$2";;
        *)    error "Invalid argument";;
    esac
}

monitorfile=${XDG_STATE_HOME}/dotfiles/monitors
[ -f "${monitorfile}" ] || error "Monitor file not found"

##@ param "primary" | "secondary"
monitor () {
    awk "/$1/{print\$2}" "${monitorfile}"
}

configure "$(monitor primary)" "$(monitor secondary)" "$1"
