#!/bin/sh

apply_default () {
    xset r rate 660 30
    setxkbmap -layout "fi" -option
    pkill unclutter
}

apply_custom () {
    xset r rate 175 60
    setxkbmap -layout us -option caps:swapescape
    exec unclutter --timeout 1 --jitter 10 --start-hidden --ignore-scrolling &
}

is_currently_default () {
    [ "$(pgrep --count unclutter)" = "0" ]
}

# $1: Message
notify () {
    [ -n "$DISPLAY" ] && notify-send -t 2000 "configure-mouse-and-keyboard" "$1"
}

case $1 in
    default)
        apply_default;;
    custom)
        apply_custom;;
    toggle)
        if is_currently_default; then
            apply_custom
            notify "Applied custom settings"
        else
            apply_default
            notify "Applied default settings"
        fi;;
    *)
        exit 1;;
esac
