#!/bin/sh

# $1: Message
error () { notify "configure-monitors" "Error: $1"; exit 1; }

# $1: Primary monitor name
# $2: Secondary monitor name
auto_configure () {
    if xrandr --listmonitors | grep --quiet --fixed-strings "$1"; then
        xrandr --output "$1" --auto --output "$2" --off
    fi
}

# $1: Primary monitor name
# $2: Secondary monitor name
# $3: Configuration
configure () {
    case $3 in
        1)    xrandr --output "$1" --auto --output "$2" --off;;
        2)    xrandr --output "$1" --off --output "$2" --auto;;
        12)   xrandr --output "$1" --auto --output "$2" --auto --right-of "$1";;
        21)   xrandr --output "$1" --auto --output "$2" --auto --left-of "$1";;
        11)   xrandr --output "$1" --auto --output "$2" --auto --same-as "$1";;
        auto) auto_configure "$1" "$2";;
        *)    error "Invalid argument";;
    esac
}

monitorfile=${DOTFILES}/state/monitors
[ -f "${monitorfile}" ] || error "Monitor file not found"

# $1: primary|secondary
monitor () {
    awk "/$1/{print\$2}" "${monitorfile}"
}

configure "$(monitor primary)" "$(monitor secondary)" "$1"
