#!/bin/sh

statefile=${XDG_STATE_HOME}/dotfiles/current-media-player
mkdir --parents "${XDG_STATE_HOME}/dotfiles"
[ -f "${statefile}" ] || echo mpv > "${statefile}"

case $# in
    0) cat "${statefile}";;
    1) echo "$1" > "${statefile}";;
    *) notify "current-media-player" "Error: Too many arguments"; exit 1;;
esac
