#!/bin/sh

gather_lines () {
    while read -r line; do echo "${line}"; done
}

choose_url () {
    grep --invert-match "^mailto:*" | dmenu -i -l 5 -p "Which URL?"
}

handle-url "$(gather_lines | urlscan --dedupe --no-browser | choose_url)"
