#!/bin/sh

# $1: Message
error () { notify "handle-podcast-urls" "Error: $1"; exit 1; }

urls=$(urlscan --dedupe --no-browser | grep --fixed-strings ".mp3")

case $(echo "${urls}" | wc --lines) in
    1) mpv --no-audio-display -- "${urls}";;
    0) error "No valid URLs found";;
    *) error "Too many valid URLs found";;
esac
