#!/bin/sh

indexfile="${MY_DOTFILES_REPO}/state/headphones-control-index"
mkdir --parents "${MY_DOTFILES_REPO}/state"
[ -f "${indexfile}" ] || echo 1 > "${indexfile}"

# $1: Error message
error () {
    if [ -n "${DISPLAY}" ]; then
        notify-send "Error: headphones-control" "$1"
    else
        echo "$1" 1>&2
    fi
    exit 1
}

# $1: "connect" | "disconnect"
# $2: Device address
connect_or_disconnect () {
    if [ -z "${DISPLAY}" ]; then
        bluetoothctl "$1" "$2"
    else
        notification=$(notify-send --print-id "Attempting to ${1}...")
        if bluetoothctl "$1" "$2"; then
            notify-send --expire-time=2000 --replace-id "${notification}" "Successfully ${1}ed"
        else
            error "Unable to $1"
        fi
    fi
}

# $1: Index
get_info () {
    bluetoothctl devices Paired | sed --quiet "${1}p"
}

# $1: Index
get_address () {
    get_info "$1" | cut --delimiter=" " --fields=2
}

# $1: Index
get_name () {
    get_info "$1" | cut --delimiter=" " --fields=3-
}

# $1: Index
rotate_index () {
    case $1 in
        "$(bluetoothctl devices Paired | wc --lines)")
            echo 1;;
        *)
            echo $(($1 + 1));;
    esac
}

# $1: New index
update_index () {
    echo "$1" > "${indexfile}"
    [ -n "${DISPLAY}" ] || return
    notify-send --replace-id=999999999 --expire-time=2000 "headphones-control" "$(get_name "$1")"
}

index=$(cat "${indexfile}")

case $1 in
    connect|disconnect)
        connect_or_disconnect "$1" "$(get_address "${index}")";;
    rotate)
        update_index "$(rotate_index "${index}")";;
    *)
        error "Invalid argument";;
esac
