#!/bin/sh

indexfile="${MY_DOTFILES_REPO}/state/headphones-control-index"
mkdir --parents "${MY_DOTFILES_REPO}/state"
[ -f "${indexfile}" ] || echo 1 > "${indexfile}"

# $1: Error message
error () {
    if [ -n "${DISPLAY}" ]; then
        notify-send "Error: headphones-control" "$1"
    else
        echo "$1" 1>&2
    fi
    exit 1
}

# $1: "connect" | "disconnect"
# $2: Device address
connect_or_disconnect () {
    if [ -z "${DISPLAY}" ]; then
        bluetoothctl "$1" "$2"
    else
        notification=$(notify-send --print-id "Attempting to ${1}...")
        if bluetoothctl "$1" "$2"; then
            notify-send --expire-time=2000 --replace-id "${notification}" "Successfully ${1}ed"
        else
            error "Unable to $1"
        fi
    fi
}

get_index () {
    cat "${indexfile}"
}

# $1: Index
rotate_index () {
    case $1 in
        1) echo 2;;
        2) echo 1;;
        *) error "Invalid device index";;
    esac
}

# $1: New index
update_index () {
    [ -n "${DISPLAY}" ] && notify-send --expire-time=2000 "headphones-control" "New headphones index: $1"
    echo "$1" > "${indexfile}"
}

get_address () {
    bluetoothctl devices Paired | cut -d' ' -f2 | sed --quiet "$(get_index)p"
}

case $1 in
    connect|disconnect)
        connect_or_disconnect "$1" "$(get_address)";;
    rotate)
        update_index "$(rotate_index "$(get_index)")";;
    *)
        error "Invalid argument";;
esac
