#!/bin/sh

number () {
    nl --number-separator=' ' --number-width=1 --starting-line-number=0
}

# $1: Directory
choose_track () {
    find "$1" -type f -printf "%P\n" | number | fzf | cut --delimiter=' ' --fields=1
}

musicpath=${HOME}/misc/media/music/all
mpvargs="--no-audio-display --shuffle --loop-playlist --volume=80"

if [ "$1" != find ]; then
    # shellcheck disable=2086 # Intentional word splitting
    mpv ${mpvargs} -- "${1:-${musicpath}}"
else
    path=${2:-${musicpath}}
    index=$(choose_track "${path}") || exit 1
    # shellcheck disable=2086 # Intentional word splitting
    find "${path}" -type f -print0 | xargs -0 mpv ${mpvargs} --playlist-start="${index}" --
fi
