#!/bin/sh

# $1: Path
listen () {
    mpv "$1" --no-audio-display --shuffle --loop-playlist --volume=80
}

case $# in
    0)
        listen "${HOME}/misc/media/music/all";;
    1)
        [ -e "$1" ] && listen "$1";;
    *)
        exit 1;;
esac
