#!/bin/sh

# $1: Message
error () { notify "media-control" "Error: $1"; exit 1; }

# $@: Arguments to forward to the player
control () {
    playerctl --player="$(current-media-player)" "$@"
}

# $1: "-" | "+"
seek () {
    lockfile=/tmp/dotfiles-media-control-seek-lock
    [ -f "${lockfile}" ] && return
    touch "${lockfile}"
    case $(control status) in
        Paused)  control position "20$1";;
        Playing) control position "5$1";;
        *)       error "Invalid player state";;
    esac
    sleep 0.5
    rm "${lockfile}"
}

toggle () {
    lockfile=/tmp/dotfiles-media-control-toggle-lock
    if [ -f "${lockfile}" ]; then
        playerctl --all-players pause &
        bluetoothctl disconnect &
        slock
    else
        {
            touch "${lockfile}"
            sleep 1
            rm "${lockfile}"
        } &
        if [ "$(control status)" = Paused ]; then
            control position 5-
            control play
        else
            control pause
        fi
    fi
}

show_current_track_title () {
    [ -n "${DISPLAY}" ] || return
    icon=/tmp/dotfiles-media-control-metadata-icon
    if title=$(control metadata title); then
        case $(control metadata mpris:artUrl | cut --delimiter=, --fields=1) in
            "data:image/"*";base64")
                control metadata mpris:artUrl | cut --delimiter=, --fields=2 | base64 --decode > "${icon}";;
            *)
                [ -f "${icon}" ] && rm "${icon}";;
        esac
        notify-send --icon="${icon}" --replace-id=999999999 --expire-time=750 "Now playing" "${title}"
    fi
}

is_at_track_beginning () {
    [ "$(control position | cut --delimiter=. --fields=1)" -lt 10 ]
}

previous () {
    if is_at_track_beginning; then
        control previous
    else
        control position 0
    fi
    show_current_track_title
}

next () {
    control next
    show_current_track_title
}

case $1 in
    toggle|play|pause) toggle;;
    next)              next;;
    previous)          previous;;
    forward)           seek +;;
    rewind)            seek -;;
    *)                 error "Invalid argument";;
esac
