#!/bin/sh

if [ -z "$*" ]; then
    exit 1
elif [ -n "${DISPLAY}" ] && ! printf "" > /dev/tty; then
    notify-send --expire-time=2000 -- "$1" "$2"
elif [ -n "$2" ]; then
    echo "$1: $2" 1>&2
else
    echo "$1" 1>&2
fi
