#!/bin/sh

error () {
    notify-send "Error: rotate-keyboard-layout" "$1"
    exit 1
}

setlayout () {
    if setxkbmap -layout "$1"
    then
        notify-send "Set keyboard layout to $1"
    else
        error "Invalid keyboard layout"
    fi
}

case $(setxkbmap -query | grep "layout:" | awk '{print $2}') in
    fi)
        setlayout "us";;
    us)
        setlayout "fi";;
    *)
        error "Unrecognized layout state";;
esac
