#!/bin/sh

# $1: Error message
error () {
    notify-send "Error: rotate-keyboard-layout" "$1"
    exit 1
}

# $1: Layout name
setlayout () {
    if setxkbmap -layout "$1"; then
        notify-send "Set keyboard layout to $1"
    else
        error "Invalid keyboard layout"
    fi
}

case $(setxkbmap -query | awk '/layout:/{print$2}') in
    fi)
        setlayout "us";;
    us)
        setlayout "fi";;
    *)
        error "Unrecognized layout state";;
esac
