#!/bin/sh

##@ param Message
error () { notify "run-tests" "Error: $1"; exit 1; }

if [ -n "$1" ]; then
    builtin cd -- "$1" || exit
fi

if [ -f "tree-sitter.json" ]; then
    tree-sitter generate && tree-sitter test
elif [ -f "CMakeCache.txt" ]; then
    cmake --build . || exit
    ctest --progress && exit
    ctest --rerun-failed --output-on-failure
elif [ -f "Cargo.toml" ]; then
    cargo test
elif [ -f "cabal.project" ]; then
    cabal test
elif [ -f "dune-project" ]; then
    opam exec dune test
elif [ -f "package.json" ]; then
    npm run test
else
    error "Could not run tests in $(pwd)"
fi
