#!/bin/sh

# $1: Message
error () { notify "run-tests" "Error: $1"; exit 1; }

run_ctest () {
    cmake --build "$1" || return
    ctest --test-dir "$1" --progress && return
    ctest --test-dir "$1" --rerun-failed --output-on-failure
}

run_cargo () {
    cargo test --manifest-path "$1/Cargo.toml"
}

# $1: Directory
run_tests () {
    if   [ -f "$1/CMakeCache.txt" ];    then run_ctest "$1"
    elif [ -f "$1/Cargo.toml" ];        then run_cargo "$1"
    else error "Could not run tests in $1"
    fi
}

case $# in
    0) run_tests .;;
    1) run_tests "$1";;
    *) error "Too many arguments";;
esac
