#!/bin/sh

# $1: Message
notify () {
    notify-send --expire-time=1000 "$1"
}

if setxkbmap -query | grep --quiet --fixed-strings "caps:swapescape"; then
    setxkbmap -option && notify "Swap off"
else
    setxkbmap -option caps:swapescape && notify "Swap on"
fi
