#!/bin/sh

##@ param Message
notify () { command notify "toggle-network" "$1"; }

nm-online --quiet --exit

case $? in
    0) nmcli radio all off && notify "Networking off";;
    1) nmcli radio all on && notify "Networking on";;
    *) notify "Error: nm-online failed"; exit 1;;
esac
