#!/bin/sh

error () {
    notify-send "Error: toggle-headphones" "$1"
    error 1
}

addressfile="$MY_DOTFILES_REPO/state/headphones-address"
[ ! -e "$addressfile" ] && error "Headphones address file not found"

headphones=$(cat "$addressfile")

case "$(bluetoothctl info "$headphones" | grep Connected)" in
  *yes*)
      bluetoothctl disconnect "$headphones";;
  *no*)
      bluetoothctl connect "$headphones";;
  *)
      error "Invalid bluetoothctl output";;
esac
