#!/bin/sh

error () { notify track "Error: $1"; exit 1; }

file=${HOME}/misc/track.txt

[ -f "${file}" ] || error "File does not exist: ${file}"
[ -n "$*" ]      || error "Expected at least one argument"

echo "$(date +%F) $*" >> "${file}"
