#!/bin/sh

file=${HOME}/misc/track.txt
today=$(date +%F)

for arg in "$@"; do
    [ -n "${arg}" ] && echo "${today} ${arg}" >> "${file}"
done

script="BEGIN {sum=0} /^${today}/ {sum+=\$2} END {print sum}"
notify "Today: $(awk "${script}" "${file}")"
