#!/bin/sh

# $1: amixer command
control () {
    amixer -q set Master "$1"
}

# $1: Message
error () {
    [ -n "${DISPLAY}" ] && notify-send "Error: volume-control" "$1"
    exit 1
}

case $1 in
    toggle)
        control toggle;;
    up)
        control 5%+;;
    down)
        control 5%-;;
    *)
        error "Invalid argument";;
esac

"${MY_DOTFILES_REPO}/scripts/update-status-bar"
