#!/bin/sh

# $1: amixer command
control () {
    amixer -q set Master "$1"
}

case $1 in
    up)     control 5%+;;
    down)   control 5%-;;
    toggle) control toggle;;
    *)      notify "volume-control" "Error: Invalid argument"; exit 1;;
esac

update-status-bar
