#!/bin/sh

if [ "$1" = audio ]; then
    shift
    args="--extract-audio --audio-format=mp3 --audio-quality=0"
else
    args="--format-sort=res:${YTDL_RES:-720}"
fi

args="${args} --embed-metadata --sponsorblock-remove=default --sponsorblock-mark=all"

# shellcheck disable=2086 # Intentional word splitting
yt-dlp ${args} "$@"
